### ISSUE TITLE
I am getting the message: "CSRF token not found or session-id not set." Do you know how to fix it?

### ISSUE THREAD

**Issue by endrebak** [jherrlin/sente-example#1]
Thanks for the example btw.

**Comment by jherrlin** [comment]
It looks like the content was provided via Shadow-cljs server and not via http-kit. 
Thats the reason why `data-csrf-token` is not provided to the client and the websocket should not start.
Ive made an update, would yo like to verify that it works for you @endrebak ?

**Comment by endrebak** [comment]
Thanks! Will try now :)

**Comment by endrebak** [comment]
You need to install the following npm deps before `lein dev` works:

`npm install react react-dom create-react-class highlight.js react-highlight.js react-flip-move`

Perhaps it should go in the docs somewhere?

**Comment by endrebak** [comment]
Huzzah, it works! Thanks :)
